# BaseGuard - Configuration file
# More information : https://unturnedstore.com/products/1380

# # # # # # # # # # # # # # # # # # # # #
# 
#    Protection controls
#
# # # # # # #
#
# Controls general protection activation
ActivationMode: Offline # Unabled - Offline - Permanent
#
# Protection applied when protection is activated.
BaseShield: 0 # from 0 to 1
#
# Controls protection activation depending on the group's type
ProtectedGroups: Any # NoGroup - InGameGroup - SteamGroup - Any
#
# Schedule when are protections enabled and disabled. Syntax helper : https://crontab.guru/
Schedule:
- Protection: On
  At: 0 0 * * 1-5
- Protection: Off
  At: 0 18 * * 1-5
- Protection: On
  At: 0 2 * * 6,0
- Protection: Off
  At: 0 10 * * 6,0
#
# Change protection for specific structures / barricades
Overrides:
- Ids: 
  - 1244
  - 1372
  - 1373
  BaseShield: 0 # from 0 to 1
  MaxShield: 0 # from 0 to 1
#
# Allow players to deal normal damage to their own structures
AllowSelfDamage: false
#
# # # # # # #


# # # # # # # # # # # # # # # # # # # # #
#
#    Guards
#
# # # # # # #
#
# Controls protection calculation
GuardMode: Ratio # Base - Cumulative - Ratio
#
# Guards list
Guards:
- Id: 458
  Range:  16 # in meters
  Shield: 0.5 # from 0 to 1
- Id: 1230
  Range: 64
  Shield: 1
#
# # # # # # #


# # # # # # # # # # # # # # # # # # # # #
#
#    Chat messages
#
# # # # # # #
#
# Configure how chat messages are sent
ChatMessages: 
  #
  # Time needed before a new message can be sent by the plugin
  DamageWarnCooldown: 10 # seconds
  #
  # Icon URL used for damage warns
  ChatIcon: https://i.imgur.com/V6Jc0S7.png
  #
  # ID of the effect to show in place of the chat message.
  EffectID: 0
  #
  # Name of the text gameobject to write the message in
  EffectTextName: Message
  #
  # How long should the effect stay on screen
  EffectDuration: 5 # seconds
#
# # # # # # #
  

# # # # # # # # # # # # # # # # # # # # #
# 
#  Anti abuse rules
#
# # # # # # #
#
# How long a player is still considered part of a group after quitting it
GroupHistoryDuration: 48 # in hours - set value to 0 to disable
# 
# Offline mode: How long does it takes for a base to be protected after being damaged when all group players disconnected
RaidDuration: 120 # in seconds - set value to 0 to disable
#
# Offline mode: How long does offline protection lasts
ProtectionDuration: 24 # in hours - set value to 0 to disable
#
# # # # # # #