# BuildGuard - Configuration file

# Control for protection activation.
# Values can be :
#   Unabled: No protection
#   Offline: Protection is active when players are offline
#   Permanent: Protection is alwyas active
ActivationMode: Offline

# Control for protection calculation.
# Values can be :
#   Base: Only the configured BaseShield is applied
#   Cumulative : In range guards shield value are added
#   Ratio : In range guards shield value are multiplied (0.5 and 0.5 will give 0.75 total shield value)
GuardMode: Base

# Base protection to apply
# Values range from 0 to 1
BaseShield: 0.2

# Only useful if ActivationMode is set to Offline
# If a player disconnects while being raided, his raiders can continue to raid his base.
# This value defines how long it needs not to take any damage for it to be protected once the player disconnects.
# Value is in seconds
ActiveRaidTimer: 120

# Protection barriades
Guards:
- Id: 458
  Range:  458
  Shield: 0.5
- Id: 1230
  Range: 32
  Shield: 1

# [Not available]
# Overwrites a protection for a structure / barricade
Overwrites:
- Id: 1373
  BaseShield: 0
  MaxShield: 0