# BuildGuard - Configuration file

# Control for protection activation.
# Values can be :
#   Unabled: No protection
#   Offline: Protection is active when players are offline
#   Permanent: Protection is alwyas active
ActivationMode: Offline

# Control for protection calculation.
# Values can be :
#   Base: Only the configured BaseShield is applied
#   Cumulative : In range guards shield value are added
#   Ratio : In range guards shield value are multiplied (0.5 and 0.5 will give 0.75 total shield value)
GuardMode: Ratio

# Base protection to apply
# Values range from 0 to 1
BaseShield: 0

# Only useful if ActivationMode is set to Offline
# Time with no damage until a raid ends after all the whole raided group disconnected before protection starts.
# Value is in seconds
ActiveRaidTimer: 120

# Minimum time between two messages sent to the player by the plugin
# Value is in seconds
DamageWarnCooldown: 10

# Icon URL used for messages
ChatIcon: https://i.imgur.com/V6Jc0S7.png

# Protection barricades and structures
Guards:
  # Id of the barricade
- Id: 458
  # Protection range (meters)
  Range:  16
  # Protection amount (from 0 to 1)
  Shield: 0.5

- Id: 1230
  Range: 64
  Shield: 1

# Overrides a protection for a structure / barricade
Overrides:
  # Id of the overrided structure or barricade
- Id: 1373
  # Protection the structure has by default (from 0 to 1)
  BaseShield: 0
  # Maximum protection the structure can have (from 0 to 1)
  MaxShield: 0