# BuildGuard - Configuration file
# More information : https://unturnedstore.com/products/1380

# # # # # # # # # # # # # # # # # # # # #
# 
#    Protection controls
#
# # # # # # #
#
# Controls general protection activation
ActivationMode: Offline # Unabled - Offline - Permanent
#
# Protection applied when protection is activated.
BaseShield: 0 # from 0 to 1
#
# Controls protection activation depending on the group's type
ProtectedGroups: Any # NoGroup - InGameGroup - SteamGroup - Any
#
# Schedule when are protections enabled and disabled. Syntax helper : https://crontab.guru/
Schedule:
- Protection: On
  At: 0 0 * * 1-5
- Protection: Off
  At: 0 18 * * 1-5
- Protection: On
  At: 0 2 * * 6,0
- Protection: Off
  At: 0 10 * * 6,0
#
# Change protection for specific structures / barricades
Overrides:
- Id: 1373
  BaseShield: 0 # from 0 to 1
  MaxShield: 0 # from 0 to 1
#
# # # # # # #


# # # # # # # # # # # # # # # # # # # # #
#
#    Guards
#
# # # # # # #
#
# Controls protection calculation
GuardMode: Ratio # Base - Cumulative - Ratio
#
# Guards list
Guards:
- Id: 458
  Range:  16 # in meters
  Shield: 0.5 # from 0 to 1
- Id: 1230
  Range: 64
  Shield: 1
#
# # # # # # #


# # # # # # # # # # # # # # # # # # # # #
#
#    Chat messages
#
# # # # # # #
#
# Time needed before a new message can be sent by the plugin
DamageWarnCooldown: 10 # in seconds
#
# Icon URL used for messages
ChatIcon: https://i.imgur.com/V6Jc0S7.png
#
# # # # # # #
  

# # # # # # # # # # # # # # # # # # # # #
# 
#  Anti abuse rules
#
# # # # # # #
#
# How long a player is still considered part of a group after quitting it
GroupHistoryDuration: 48 # in hours - set value to 0 to disable
# 
# Offline mode: How long does it takes for a base to be protected after being damaged when all group players disconnected
RaidDuration: 120 # in seconds - set value to 0 to disable
#
# Offline mode: How long does offline protection lasts
ProtectionDuration: 24 # in hours - set value to 0 to disable
#
# # # # # # #